# Generated by Django 2.0 on 2019-12-03 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_auto_20191202_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.AddField(
            model_name='view',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
