# Generated by Django 2.0 on 2019-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20191202_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='view_counts',
            field=models.IntegerField(default=0),
        ),
    ]
