# Generated by Django 2.0 on 2019-12-11 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_view_view_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
