# Generated by Django 3.0.3 on 2020-03-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_inappmessage_mobiledevice_mobilenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiledevice',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='mobilenotification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='InAppMessage',
        ),
        migrations.DeleteModel(
            name='MobileDevice',
        ),
        migrations.DeleteModel(
            name='MobileNotification',
        ),
    ]
