# Generated by Django 2.0 on 2019-12-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[(1, 'Home address'), (2, 'Shipping address')], max_length=120),
        ),
    ]
