# Generated by Django 2.0 on 2019-12-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20191223_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home address'), ('shipping', 'Shipping address')], max_length=120),
        ),
    ]
