# Generated by Django 2.0 on 2019-12-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
