# Generated by Django 2.0 on 2019-12-17 11:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20191217_0337'),
        ('cart', '0007_productcart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupons'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
