# Generated by Django 2.0 on 2019-12-17 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20191217_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
