# Generated by Django 2.0 on 2019-12-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ('value',)},
        ),
    ]
