# Generated by Django 2.0 on 2019-12-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
